//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace praktikaDE.DataBase_Folder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoParking_DBEntities : DbContext
    {
        public static AutoParking_DBEntities _context;

        public AutoParking_DBEntities()
            : base("name=AutoParking_DBEntities")
        {
        }

        public static AutoParking_DBEntities GetContext()
        {
            if (_context == null)
                _context = new AutoParking_DBEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Автомобили> Автомобили { get; set; }
        public DbSet<Пользователи> Пользователи { get; set; }
        public DbSet<Состояния> Состояния { get; set; }
        public DbSet<Сотрудники> Сотрудники { get; set; }
        public DbSet<Специальности> Специальности { get; set; }
    }
}
