//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace praktikaDE.DataBase_Folder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Автомобили
    {
        public int Код_автомобиля { get; set; }
        public int Код_сотрудника { get; set; }
        public string Марка { get; set; }
        public string Модель { get; set; }
        public int Пробег { get; set; }
        public int Код_состояния { get; set; }
    
        public virtual Состояния Состояния { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
