//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace praktikaDE.DataBase_Folder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        public int Код_пользователя { get; set; }
        public int Код_сотрудника { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public Nullable<System.DateTime> Дата_последнего_входа { get; set; }
        public bool Заблокитрован { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
