//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace praktikaDE.DataBase_Folder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        public Сотрудники()
        {
            this.Автомобили = new HashSet<Автомобили>();
            this.Пользователи = new HashSet<Пользователи>();
        }
    
        public int Код_сотрудника { get; set; }
        public int Код_специальности { get; set; }
        public string ФИО { get; set; }
    
        public virtual ICollection<Автомобили> Автомобили { get; set; }
        public virtual ICollection<Пользователи> Пользователи { get; set; }
        public virtual Специальности Специальности { get; set; }
    }
}
